In [1]:
import os
os.environ['http_proxy'] = 'http://127.0.0.1:7897'
os.environ['https_proxy'] = 'http://127.0.0.1:7897'

In [2]:
import torch

a = torch.tensor([1,1,1])
b = torch.tensor([2,2,2])

c = torch.matmul(a,b)
c

tensor(6)

In [6]:
a = torch.ones(2,2,2,2)
a

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [36]:
a = torch.rand(2,4,3)
b = a
b

tensor([[[0.1022, 0.1359, 0.0041],
         [0.2414, 0.0209, 0.5436],
         [0.5185, 0.1570, 0.1426],
         [0.4008, 0.3987, 0.7051]],

        [[0.5782, 0.9397, 0.6233],
         [0.4860, 0.2973, 0.0798],
         [0.5823, 0.9677, 0.4493],
         [0.4259, 0.1424, 0.4475]]])

In [46]:
c = b.transpose(1,2)
c

tensor([[[0.1022, 0.2414, 0.5185, 0.4008],
         [0.1359, 0.0209, 0.1570, 0.3987],
         [0.0041, 0.5436, 0.1426, 0.7051]],

        [[0.5782, 0.4860, 0.5823, 0.4259],
         [0.9397, 0.2973, 0.9677, 0.1424],
         [0.6233, 0.0798, 0.4493, 0.4475]]])

In [51]:
from torch import nn

class Module1(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.lay1 = nn.Linear(3,5)
        self.activation = nn.ReLU()
        self.lay2 = nn.Linear(5,3)
    
    def forward(self, x):
        x = self.lay1(x)
        x = self.activation(x)
        x = self.lay2(x)
        return x

class Module2(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.layer = nn.ModuleList([Module1() for _ in range(2)])

    def forward(self, x):
        for layer in self.layer:
            x = layer(x)
        return x


module2 = Module2()

x = torch.rand(4,3)

y = module2(x)

print(x)
print(y)

tensor([[0.3625, 0.6105, 0.5483],
        [0.5940, 0.5018, 0.0945],
        [0.5202, 0.8446, 0.0271],
        [0.8126, 0.2335, 0.3375]])
tensor([[0.0403, 0.4767, 0.2745],
        [0.0346, 0.4733, 0.2707],
        [0.0572, 0.5141, 0.2891],
        [0.0281, 0.4560, 0.2662]], grad_fn=<AddmmBackward0>)
