In [7]:
import torch

a = [[1,2,3],[4,5,6]]

print(torch.tensor(a,device='mps'))

tensor([[1, 2, 3],
        [4, 5, 6]], device='mps:0')


In [10]:
print(torch.empty(2,3).to('mps'))

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='mps:0')


In [4]:
print(torch.randn(2,3))

tensor([[ 1.0008, -0.1771, -0.4713],
        [-1.1792, -1.0151,  0.0568]])


In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(torch.from_numpy(a))

tensor([[1, 2, 3],
        [4, 5, 6]])


In [20]:
a = torch.ones(2,3,4,dtype=torch.float).to('mps')
print(a.shape)
print(a.dtype)
print(a.device)

torch.Size([2, 3, 4])
torch.float32
mps:0


In [22]:
a = np.array([[1,2,3],[4,5,6]])
b = torch.tensor([[1,1,1],[2,2,2]])
a = torch.tensor(a)

print(a)
print(b)
print(a + b)
print(a * b)
print(a ** 2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 1, 1],
        [2, 2, 2]])
tensor([[2, 3, 4],
        [6, 7, 8]])
tensor([[ 1,  2,  3],
        [ 8, 10, 12]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [25]:
a = torch.rand(3,4)
b = torch.rand(4,5)
print(torch.mm(a,b))
print(a@b)

tensor([[0.7010, 0.6323, 1.9828, 0.7467, 1.1283],
        [0.6863, 0.7227, 1.9545, 0.7776, 1.2277],
        [0.2459, 0.3176, 0.9240, 0.5451, 0.4865]])
tensor([[0.7010, 0.6323, 1.9828, 0.7467, 1.1283],
        [0.6863, 0.7227, 1.9545, 0.7776, 1.2277],
        [0.2459, 0.3176, 0.9240, 0.5451, 0.4865]])


In [32]:
x = torch.rand(2,3,4)
print(x)
y = x.reshape(2,12)
# print(y)
z = x.transpose(0,2)
print(z)
z = x.permute(2,1,0)
# print(z)

tensor([[[0.2884, 0.6585, 0.9124, 0.5040],
         [0.1522, 0.2788, 0.1970, 0.5147],
         [0.8295, 0.8570, 0.4736, 0.8391]],

        [[0.8821, 0.0687, 0.9782, 0.8758],
         [0.0161, 0.6023, 0.6664, 0.8814],
         [0.7484, 0.1360, 0.9875, 0.8102]]])
tensor([[[0.2884, 0.8821],
         [0.1522, 0.0161],
         [0.8295, 0.7484]],

        [[0.6585, 0.0687],
         [0.2788, 0.6023],
         [0.8570, 0.1360]],

        [[0.9124, 0.9782],
         [0.1970, 0.6664],
         [0.4736, 0.9875]],

        [[0.5040, 0.8758],
         [0.5147, 0.8814],
         [0.8391, 0.8102]]])


In [47]:
w = torch.tensor([3.0],requires_grad=True)
b = torch.tensor([2.0],requires_grad=True)
x = torch.tensor([4.0],requires_grad=True)

y = w*x + b
# y.requires_grad_()
target = torch.tensor([10.0])
loss = (y - target) ** 2
print(y)
print(loss)

y.retain_grad()
loss.backward()
# y.backward()
print(y.grad)
print(x.grad)
print(w.grad)
print(b.grad)

tensor([14.], grad_fn=<AddBackward0>)
tensor([16.], grad_fn=<PowBackward0>)
tensor([8.])
tensor([24.])
tensor([32.])
tensor([8.])
