In [1]:
import os
os.environ['http_proxy'] = 'http://127.0.0.1:7897'
os.environ['https_proxy'] = 'http://127.0.0.1:7897'

In [5]:
import torch

a = torch.tensor([[1,2,3],[4,5,6]])

b=a[:,None,None,:]
print(b)



tensor([[[[1, 2, 3]]],


        [[[4, 5, 6]]]])


In [ ]:
'''使用GPU进行推理'''
from transformers import AutoTokenizer, AutoModel
import torch
tokenizer = AutoTokenizer.from_pretrained("../models/bert-base-cased")
model = AutoModel.from_pretrained("../models/bert-base-cased", device_map="cuda")

raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]
sequence = "Using a Transformer model is simple"

inputs = tokenizer(raw_inputs[0],raw_inputs[1], padding=True, truncation=True, return_tensors="pt")

In [11]:
for key,value in inputs.items():
    print(key)
    print(value)
print(inputs.sequence_ids())

input_ids
tensor([[  101,   146,   112,  1396,  1151,  2613,  1111,   170, 20164, 10932,
          2271,  7954,  1736,  1139,  2006,  1297,   119,   102,   146,  4819,
          1142,  1177,  1277,   106,   102]])
token_type_ids
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
         1]])
attention_mask
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1]])
[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, 1, 1, 1, 1, 1, 1, None]
